### ISSUE TITLE
Option to open in browser by default, preview tab not required.

### ISSUE THREAD

**Issue by johtso** [zenclabs/reactpreview#31]
Currently a preview tab is always opened in a vscode tab, and if you want to instead view it in a browser you need to click the link, and then move the preview tab out of its split pane (but not close it).

I'm wondering if an option to open in browser by default would be worthwhile, and the possibility to not require a preview tab in-app to have the preview running? Maybe not worthwhile.. but something like the floating debugger bar could be an option?
<img width="242" alt="image" src="https://user-images.githubusercontent.com/830800/123708521-80406d80-d863-11eb-8cda-2b63efed7271.png">

Just throwing ideas around, not sure what the ideal approach is here. I do think currently it is a little clunky if you don't want to have the preview in-app. Low priority regardless.

**Comment by fwouts** [comment]
I was waiting until someone brought this up 😄

An alternative would be to open the browser and automatically kill the preview server when it detects that the browser tab has been closed after a few seconds (this is possible because there's a websocket connection between the two, so when it's interrupted we know). Thoughts?

**Comment by fwouts** [comment]
Hi @johtso, I'm sorry this took a while but FYI this is coming in the next release next week :)

**Comment by fwouts** [comment]
This is now live in v0.6.2!
